### ISSUE TITLE
Feature request: refund function

### ISSUE THREAD

**Issue by Hocoh** [jmcollin78/payplug-nodejs#1]
After having abort a payment does the payment refunded? It would be awesome if it's not the case to add this feature. 
thanks for your awesome work !

**Comment by jmcollin78** [comment]
Aborting a payment does not refund if funds have been captured.  I will not have time to implement this feature for now but I can easily helps you if you decide to implement it.

I leave the case open.

**Comment by jmcollin78** [comment]
No decision about this feature.
